version: '3.8'

services:
  django-web:
    build: .
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DB: 'GenerateMotif'
    
  mysql-db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'GenerateMotif'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
