# Gunakan base image Python
FROM python:3.9

# Salin kode aplikasi ke dalam container
COPY . /app

# Tentukan direktori kerja
WORKDIR /app

# Instal dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Expose port yang digunakan oleh Django
EXPOSE 8000

# Perintah default saat container dijalankan
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
