# # docker paling update 
version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: project_mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'GenerateMotif'
      MYSQL_TCP_PORT: '3308'
    ports:
      - "3308:3308"
  
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_django
    # command: sh -c "sleep 10 && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py seed_accounts && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - mysql-db

volumes:
  mysql-data:
    driver: local